### PR TITLE
url has changed for mirror

### PR DESCRIPTION
**Pull request by iheartwhiskey**
http://releases.ubuntu.com/trusty/ubuntu-14.04.2-server-amd64.iso is the new url for the iso mirror. i apologize i am new on github, didn't catch the url was the same in all three files.

### CODE REVIEW

**Comment by ssk2** [comment]
Hey @iheartwhiskey - could you update the second part of the URL too? i.e. `ubuntu-14.04-server-amd64.iso` -> `ubuntu-14.04.2-server-amd64.iso` 

Thanks so much for the contribution!

**Comment by iheartwhiskey** [comment]
Hi,

    I updated as requested. 

cheers

**Comment by ssk2** [comment]
Great, could you squash your commits and I'll merge?

**Comment by iheartwhiskey** [comment]
sure my git's a little rusty but i'll do that right :D thanks!

**Comment by ssk2** [comment]
`git rebase -i 84ff0bcc4f7764111cf93ef664a57b349f7d2eab` should do it. Just change the last three commits there to `squash` instead of `pick` and you're good to go!

**Comment by iheartwhiskey** [comment]
i think i blew up something haha. since it's a small change i'll just make a new request all in one. i don't want to waste your time.  i gotta re learn my gitness anyway :D

**Pull request closed without merging**
